/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courier.service.system;

/**
 *
 * @author Nazar & Kamilla
 */
public class Managing_Staff_Main_Form extends javax.swing.JFrame {

    /**
     * Creates new form Managing_Staff_Main_Form
     */
    public Managing_Staff_Main_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUserAccount = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        signoutbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Courier Service System");

        jPanel1.setBackground(new java.awt.Color(69, 123, 157));

        btnUserAccount.setBackground(new java.awt.Color(69, 123, 157));
        btnUserAccount.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnUserAccount.setForeground(new java.awt.Color(241, 250, 238));
        btnUserAccount.setText("User Account");
        btnUserAccount.setBorderPainted(false);
        btnUserAccount.setContentAreaFilled(false);
        btnUserAccount.setOpaque(true);
        btnUserAccount.setPreferredSize(new java.awt.Dimension(153, 23));
        btnUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountActionPerformed(evt);
            }
        });

        btnOrder.setBackground(new java.awt.Color(69, 123, 157));
        btnOrder.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(241, 250, 238));
        btnOrder.setText("Order Management");
        btnOrder.setBorderPainted(false);
        btnOrder.setContentAreaFilled(false);
        btnOrder.setOpaque(true);
        btnOrder.setPreferredSize(new java.awt.Dimension(153, 23));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnFeedback.setBackground(new java.awt.Color(69, 123, 157));
        btnFeedback.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnFeedback.setForeground(new java.awt.Color(241, 250, 238));
        btnFeedback.setText("Feedback Management");
        btnFeedback.setBorderPainted(false);
        btnFeedback.setContentAreaFilled(false);
        btnFeedback.setOpaque(true);
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(69, 123, 157));
        btnReport.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        btnReport.setForeground(new java.awt.Color(241, 250, 238));
        btnReport.setText("Report");
        btnReport.setBorderPainted(false);
        btnReport.setContentAreaFilled(false);
        btnReport.setOpaque(true);
        btnReport.setPreferredSize(new java.awt.Dimension(153, 23));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        signoutbtn.setBackground(new java.awt.Color(255, 51, 51));
        signoutbtn.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        signoutbtn.setForeground(new java.awt.Color(241, 250, 238));
        signoutbtn.setText("Sign Out");
        signoutbtn.setBorderPainted(false);
        signoutbtn.setContentAreaFilled(false);
        signoutbtn.setFocusPainted(false);
        signoutbtn.setOpaque(true);
        signoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signoutbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFeedback)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountActionPerformed
        jPanel2.removeAll();
        jPanel2.setVisible(false);
        jPanel2.setVisible(true);
        UserAccount pa3 = new UserAccount();
        pa3.setSize(jPanel2.getWidth(), jPanel2.getHeight());
        pa3.pack();
        jPanel2.add(pa3.getContentPane());
    }//GEN-LAST:event_btnUserAccountActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        jPanel2.removeAll();
        jPanel2.setVisible(false);
        jPanel2.setVisible(true);
        OrderForm pa3 = new OrderForm();
        pa3.setSize(jPanel2.getWidth(), jPanel2.getHeight());
        pa3.pack();
        jPanel2.add(pa3.getContentPane());
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        jPanel2.removeAll();
        jPanel2.setVisible(false);
        jPanel2.setVisible(true);
        FeedbackForm pa3 = new FeedbackForm();
        pa3.setSize(jPanel2.getWidth(), jPanel2.getHeight());
        pa3.pack();
        jPanel2.add(pa3.getContentPane());
    }//GEN-LAST:event_btnFeedbackActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        jPanel2.removeAll();
        jPanel2.setVisible(false);
        jPanel2.setVisible(true);
        ReportForm pa3 = new ReportForm();
        pa3.setSize(jPanel2.getWidth(), jPanel2.getHeight());
        pa3.pack();
        jPanel2.add(pa3.getContentPane());
    }//GEN-LAST:event_btnReportActionPerformed

    private void signoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutbtnActionPerformed
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_signoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Managing_Staff_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Managing_Staff_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Managing_Staff_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Managing_Staff_Main_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Managing_Staff_Main_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnUserAccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton signoutbtn;
    // End of variables declaration//GEN-END:variables
}
